airflow:
  enabled: true
  airflow:
    image:
      repository: helxplatform/roger
      tag: "0.3.0"
      pullPolicy: Always
    executor: KubernetesExecutor
    config:
      AIRFLOW__CORE__LOAD_EXAMPLES: "FALSE"
      AIRFLOW__CORE__LOGGING_LEVEL: "INFO"
      AIRFLOW__SCHEDULER__SCHEDULE_AFTER_TASK_EXECUTION: "FALSE"
      # Provide http://<URL to nginx >/<web-prefix>
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "TRUE"
      # this could would work in any ingress url.
      AIRFLOW__WEBSERVER__BASE_URL: "http://0.0.0.0/airflow"
    extraEnv:
      - name: ROGER_ELASTICSEARCH_HOST
        valueFrom:
          configMapKeyRef:
            name: search-elastic-config
            key: host
      - name: ROGER_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: search-elastic-secret
            key: password
      - name: ROGER_ELASTICSEARCH_USERNAME
        valueFrom:
          secretKeyRef:
            name: search-elastic-secret
            key: username
      - name: ROGER_REDISGRAPH_HOST
        valueFrom:
          configMapKeyRef:
            name: search-redis-config
            key: host
      - name: ROGER_REDISGRAPH_GRAPH
        valueFrom:
          configMapKeyRef:
            name: search-redis-config
            key: graph
      - name: ROGER_REDISGRAPH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: search-redis-secret
            key: password
      - name: ROGER_REDISGRAPH_PORT
        valueFrom:
          configMapKeyRef:
            name: search-redis-config
            key: port
      - name: ROGER_DATA_DIR
        valueFrom:
          configMapKeyRef:
            name: search-data-config
            key: data_directory
      - name: ROGER_ELASTICSEARCH_NBOOST__HOST
        value: nboost $ TODO compute this
      - name: ROGER_INDEXING_TRANQL__ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: search-data-config
            key: tranql_endpoint
        value:
      - name: AIRFLOW__CORE__FERNET_KEY
        valueFrom:
          secretKeyRef:
            # Same as airflow.configSecretsName
            name: airflow-config-secrets
            key: fernet-key
    extraVolumeMounts:
      - name: airflow-data
        mountPath: /opt/airflow/share/data
    extraVolumes:
      - name: airflow-data
        persistentVolumeClaim:
          claimName: search-data

    usersUpdate: true
    configSecretsName: airflow-config-secrets

    # Resource config for all task runner pods.
    kubernetesPodTemplate:
      resources: {}
        # requests:
          # memory: 1Gi

  externalRedis:
    host: ""
    passwordSecret: search-redis-secret
    passwordSecretKey: password

  dags:
    gitSync:
      enabled: true
      repo: "https://github.com/helxplatform/roger.git"
      repoSubPath: "dags"
      branch: "main"
      revision: "HEAD"
      syncWait: 60

  logs:
    path: /opt/airflow/share/logs
    persistence:
      enabled: true
      storageClass: "" ## WARNING: your StorageClass MUST SUPPORT `ReadWriteMany`
      accessMode: ReadWriteMany
      size: 1Gi

  redis:
    enabled: false

  flower:
    enabled: false

  workers:
    enabled: false

api:
  image:
    repository: helxplatform/dug
    tag: "2.3.0"
    pullPolicy: IfNotPresent

  appName: webserver
  deployment:
    apiPort: 5551
    apiWorkers: 4
    apiTimeout: 10
    extraEnv: []
    logLevel: INFO
    imagePullSecrets: []
    resources: {}
  service:
    name: search-api
    type: ClusterIP
    annotations: {}
    apiPort: "5551"
  debug: false

elasticsearch:
  enabled: true
  imageTag: "7.12.0"
  clusterName: search-elasticsearch
  replicas: 1

  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: search-elastic-secret
          key: password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: search-elastic-secret
          key: username

nboost:
  enabled: false

persistence:
  storageClass: ""
  pvcSize: 1Gi

redis:
  enabled: true
  persistence:
    existingClaim: "redis-data"
  usePassword: true
  clusterDomain: mitchell-cluster
  auth:
    enabled: true
    existingSecret: search-redis-secret
    existingSecretPasswordKey: password
  image:
    repository: redislabs/redisgraph
    tag: 2.2.14
  master:
    resources:
      requests:
        memory: 30Mi
        cpu: 10m
      limits:
        memory: 12Gi
        cpu: 500m
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
    service:
      port: 6379
  replica:
    replicaCount: 1
    resources:
      requests:
        memory: 30Mi
        cpu: 300m
      limits:
        memory: 12Gi
        cpu: 1000m
    readinessProbe:
      enabled: false
    customReadinessProbe:
      # Two reasons here, to use large number here
      # 1. incase a restart of a pod happened, and the redis pod already had data there is some delay before
      # data is loaded into memory. During that time if traffic is routed to the pod starting up, errors would surface.
      # 2. HPA would consider calculation after readiness is met, for determining if an increase is needed. But if the pod
      # is not ready yet its set aside of calculation (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details)
      # There is  an expected spike of cpu during initial loading of data. And would be beneficial to avoid
      # HPA considering this a real spike further creating more pods, and they spike, more would be created.
      initialDelaySeconds: 10
      periodSeconds: 10
      # We expect the first "few" pings to redis to fail when its loading and we want to tolerate those.
      # We could increase initial delay but that would make an empty db startup delayed. So by setting failure threshold
      # to a very high number we can eventually detect it's readiness in about ((period + timeout) * failure) ( 10 + 1  mins max). Setting this to low with initial delay also low
      # would cause restarts of the pod.
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 60
      exec:
        command:
          - /health/ping_readiness_local.sh
          - "1"
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
    service:
      port: 6379
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPU: 90

secrets:
  elastic:
    name: search-elastic-secret
    user: elastic
    userKey: username
    passwordKey: password
  redis:
    name: search-redis-secret
    passwordKey: password

tranql:
  enabled: true
  existingRedis:
    host: "search-redis-replicas"
    port: 6379
    secret: search-redis-secret
    secretPasswordKey: password
  webPrefix: "/tranql"  # TODO this and the one below should be combined
  extraEnv:
    - name: WEB_PATH_PREFIX
      value: "/tranql"
  gunicorn:
    workerCount: 4
    # Some ops like /tranql/schema endpoint take quite a while in large graph.
    workerTimeout: 600
  redis:
    enabled: false