apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search.api.web.fullname" . }}
  labels:
    app: {{ .Values.api.appName}}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.api.appName}}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.api.deployment.imagePullSecrets | nindent 8 }}
      containers:
      - image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        name: {{ include "search.api.web.fullname" . }}-container
        env: {{ include "search.api.web.deploymentEnv" . | nindent 10 }}
        ports:
          - containerPort: {{ .Values.api.deployment.apiPort }}
        # command: 
        # - /bin/sh
        # tty: True
        # stdin: True
        command: [
            "gunicorn",
            "--workers={{ .Values.api.deployment.apiWorkers | default 4 }}",
            "--bind=0.0.0.0:{{ .Values.api.deployment.apiPort }}",
            "--timeout={{ .Values.api.deployment.apiTimeout }}",
            "--log-level={{ .Values.api.deployment.logLevel | default "INFO"}}",
            "--worker-class",
            "uvicorn_custom.SubPathWorker",
            "dug.server:APP"
        ]
        resources:
          {{- toYaml .Values.api.deployment.resources | nindent 10 }}
        volumeMounts:

          - name: program-config
            mountPath: "/home/dug/dug/program-names.json"
            subPath: "program_names.json"

          - name: consent-id-config
            mountPath: "/home/dug/dug/consent-id.json"
            subPath: "consent_id.json"

          - name: missing-studies-config
            mountPath: "/home/dug/dug/missing_studies.json"
            subPath: "missing_studies.json"
          - name: missing-programs-config
            mountPath: "/home/dug/dug/missing_programs.json"
            subPath: "missing_programs.json"

          - name: gunicorn-config
            mountPath: "/home/dug/dug/uvicorn_custom.py"
            subPath: "uvicorn_custom.py"
          - name: elastic-ca
            mountPath: "{{ .Values.api.certMountPath }}"
            subPath: "ca.crt"
      volumes:
      - name: gunicorn-config
        configMap:
          name: {{ include "search.api.web.fullname" . }}-gunicorn-conf
          defaultMode: 0777
      - name: program-config
        configMap:
          name: {{ include "search.api.web.fullname" . }}-program-names
          defaultMode: 0777
      - name: consent-id-config
        configMap:
          name: {{ include "search.api.web.fullname" . }}-consent-id-config
          defaultMode: 0777
      - name: missing-programs-config
        configMap:
          name: {{ include "search.api.web.fullname" . }}-missing-programs-config
          defaultMode: 0777
      - name: missing-studies-config
        configMap:
          name: {{ include "search.api.web.fullname" . }}-missing-studies-config
          defaultMode: 0777
      - name: elastic-ca
        secret:
          secretName: {{ include "search.api.elasticsearch.uname" . }}-certs
          defaultMode: 0777
