apiVersion: v1
kind: Service
metadata:
  name: {{ include "search.api.web.fullname" . }}
  {{- if .Values.api.service.annotations }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4}}
  {{- end }}
  labels:
    app: {{ .Values.api.appName }}
    {{- include "search.api.labels" . | nindent 4 }}
spec:
  ports:
    - name: api-port
      protocol: TCP
      port: {{ .Values.api.service.apiPort }}
      targetPort: {{ .Values.api.deployment.apiPort }}
  selector:
    app: {{ .Values.api.appName }}
  type: {{ .Values.api.service.type }}
---
{{ if .Values.chat.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "search.api.web.fullname" . }}-chat
  {{- if .Values.api.service.annotations }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4}}
  {{- end }}
  labels:
    app: {{ .Values.api.appName }}-chat
    {{- include "search.api.labels" . | nindent 4 }}
spec:
  ports:
    - name: chat-port
      protocol: TCP
      port: {{ .Values.chat.apiPort }}
      targetPort: {{ .Values.chat.apiPort }}
  selector:
    app: {{ .Values.api.appName }}-chat
  type: {{ .Values.chat.service.type }}
{{ end }}
---
{{ if .Values.chat_2.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "search.api.web.fullname" . }}-chat-2
  {{- if .Values.api.service.annotations }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4}}
  {{- end }}
  labels:
    app: {{ .Values.api.appName }}-chat-2
    {{- include "search.api.labels" . | nindent 4 }}
spec:
  ports:
    - name: chat-port
      protocol: TCP
      port: {{ .Values.chat.apiPort }}
      targetPort: {{ .Values.chat.apiPort }}
  selector:
    app: {{ .Values.api.appName }}-chat-2
  type: {{ .Values.chat_2.service.type }}
{{ end }}
