{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "search-elastic-secret"
{{- if or .Release.IsInstall ( not (lookup "v1" "Secret" .Release.Namespace ( "search-elastic-secret" ))) }}
stringData:
  username: {{ "elastic" | quote }}
data:
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{- else }}
stringData:
  username: {{ "elastic" | quote }}
data:
  password: {{ index (lookup "v1" "Secret" .Release.Namespace ( "search-elastic-secret" )).data "password" }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.redis.name }}
data:
  {{- if or .Release.IsInstall ( not (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.redis.name ))) }}
  {{ .Values.secrets.redis.passwordKey }}: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  {{ .Values.secrets.redis.passwordKey }}: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.redis.name )).data .Values.secrets.redis.passwordKey }}
  {{ end }}
#---
{{/*#apiVersion: v1*/}}
{{/*#kind: Secret*/}}
{{/*#metadata:*/}}
{{/*#  name: {{ .Values.airflow.auth.existingSecret }}*/}}
{{/*#data:*/}}
{{/*#  {{- if or .Release.IsInstall (not ( lookup "v1" "Secret" .Release.Namespace ( .Values.airflow.auth.existingSecret ) ))  }}*/}}
{{/*#  airflow-fernet-key: {{ randAlphaNum 32 | b64enc | b64enc | quote }}*/}}
{{/*#  {{ else }}*/}}
{{/*#  airflow-fernet-key: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.airflow.auth.existingSecret )).data "airflow-fernet-key" }}*/}}
{{/*#  {{ end }}*/}}
---
{{ if .Values.ingress.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-htpasswd
data:
  auth: {{ htpasswd .Values.ingress.basicAuth.username .Values.ingress.basicAuth.password | b64enc | quote }}
{{ end }}
